name: ht_preferences_inmemory
description: Inmemory implementation of the `HtPreferencesClient` interface. It's primarily intended for development purposes.
publish_to: none
repository: https://github.com/headlines-toolkit/ht-preferences-inmemory

environment:
  sdk: ^3.7.0

dependencies: 
  ht_preferences_client:
    git:
        url: https://github.com/headlines-toolkit/ht-preferences-client.git

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
